project:
  type: website
  output-dir: docs
website:
  title: "Week 4: Regression modelling part 2"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - about.qmd
format:
  pdf: default
  html:
    theme: cosmo
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual

